version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production

    environment:
      - NODE_ENV=production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=090912
      - POSTGRES_DB=test_app
      - POSTGRES_DB=5432

    command: sh -c "npm run prod"
