version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    volumes:
      - ./:/test-app
      - /test-app/node_modules
    environment:
      - PORT=4000
      - APP_NAME=test-app

    deploy:
      replicas: 2

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 090912
      POSTGRES_DB: test_app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

